export const locationsSortFields = [
  "_id",
  "name",
  "rate",
  "popular",
  "rating",
  "newest",
];

export const locationTypeList = [
  "istorychne-mistse",
  "ozero",
  "richka",
  "kempinh",
  "kanyon",
  "zapovidnyk",
  "termalni-dzherela",
  "lis",
  "natsionalnyi-park",
  "vodospad",
  "hory",
  "miskyi-vidpochynok",
  "hirskolyzhnyi-kurort",
  "zamok",
  "spa-kurort",
  "pechera",
  "more",
  "plyazh",
];

export const regionTypeList = [
  "podillya",
  "halychyna",
  "volyn",
  "khmelnychchyna",
  "luhanshchyna",
  "bukovyna",
  "sumshchyna",
  "shatski-ozera",
  "kyyivshchyna",
  "vinnychchyna",
  "poltavshchyna",
  "slobozhanshchyna",
  "zhytomyrshchyna",
  "khersonshchyna",
  "ukrainski-karpaty",
  "dnistrovskyi-kanyon",
  "azovske-uzberezhzhya",
  "naddnipryanshchyna",
  "ternopilshchyna",
  "kharkivshchyna",
  "bessarabiya",
  "odeshchyna",
  "cherkashchyna",
  "zaporizhzhya",
  "lvivshchyna",
  "ivano-frankivshchyna",
  "rivnenshchyna",
  "dnipropetrovshchyna",
  "polissya",
  "chornomorske-uzberezhzhya",
  "mykolayivshchyna",
  "donechchyna",
  "zakarpattya",
  "hutsulshchyna",
  "chernihivshchyna",
  "kirovohradshchyna",
];

// export const locationTypeList = [
//   "Історичне місце",
//   "Озеро",
//   "Річка",
//   "Кемпінг",
//   "Каньйон",
//   "Заповідник",
//   "Термальні джерела",
//   "Ліс",
//   "Національний парк",
//   "Водоспад",
//   "Гори",
//   "Міський відпочинок",
//   "Гірськолижний курорт",
//   "Замок",
//   "Спа-курорт",
//   "Печера",
//   "Море",
//   "Пляж",
// ];

// export const regionTypeList = [
//   "Поділля",
//   "Галичина",
//   "Волинь",
//   "Хмельниччина",
//   "Луганщина",
//   "Буковина",
//   "Сумщина",
//   "Шацькі озера",
//   "Київщина",
//   "Вінниччина",
//   "Полтавщина",
//   "Слобожанщина",
//   "Житомирщина",
//   "Херсонщина",
//   "Українські Карпати",
//   "Дністровський каньйон",
//   "Азовське узбережжя",
//   "Наддніпрянщина",
//   "Тернопільщина",
//   "Харківщина",
//   "Бессарабія",
//   "Одещина",
//   "Черкащина",
//   "Запоріжжя",
//   "Львівщина",
//   "Івано-Франківщина",
//   "Рівненщина",
//   "Дніпропетровщина",
//   "Полісся",
//   "Чорноморське узбережжя",
//   "Миколаївщина",
//   "Донеччина",
//   "Закарпаття",
//   "Гуцульщина",
//   "Чернігівщина",
//   "Кіровоградщина",
// ];
